server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_social
    username: postgres
    password: admin
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.github.nguyenhaminhtuan: DEBUG
    org.hibernate.SQL: DEBUG