server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always

spring:
  profiles:
    active: local
  main:
    banner-mode: off
  session:
    store-type: redis
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    table: schema_history
    baseline-on-migrate: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    root: WARN
    org.springframework.web: ${LOG_LEVEL}
    org.hibernate: ERROR