server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_social
    username: postgres
    password: admin
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG